http:
  routers:
    ssafy-webhook:
      rule: >-
        Host(`ssafy.kkh-hub.tech`) &&
        (Path(`/healthz`) ||
        Path(`/webhooks/gitlab`) ||
        Path(`/webhooks/mattermost/outgoing`) ||
        Path(`/commands/mattermost/a502`))
      entryPoints:
        - websecure
      service: ssafy-webhook
      tls:
        certResolver: letsencrypt

  services:
    ssafy-webhook:
      loadBalancer:
        passHostHeader: true
        healthCheck:
          path: /healthz
          interval: 30s
          timeout: 5s
        servers:
          - url: http://ssafy-webhook-receiver:8000
